const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 125,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality pant',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 165,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pant',
    },
    {
      name: 'Barca home jersey',
      slug: 'barca-home-jersey',
      category: 'jerseys',
      image: '/images/p5.jpg',
      price: 110,
      countInStock: 40,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 22,
      description: 'high quality jersey',
    },
    {
      name: 'Real Madrid home jersey',
      slug: 'real-home-jersey',
      category: 'jerseys',
      image: '/images/p6.jpg',
      price: 110,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 22,
      description: 'high quality jersey',
    },
  ],
};
export default data;
